remote_theme: "dracula/gh-pages"
title: TUMGAD
description: Exercise generation and helpful materials for the Introduction to Algorithms and Data Structures 📚
icon: /docs/favicon.png
show_header: true
