remote_theme: "dracula/gh-pages"
show_header: "false"
icon: docs/favicon.png
title: TUMGAD
description: Exercise generation and helpful materials for the Introduction to Algorithms and Data Structures 📚
